### ISSUE TITLE
fees vs block reward (units are inconsistent)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin-explorer#10]
For example -
 https://grinexplorer.net/block/5df58803ba2df2eb3f649bd1cae11e93ffb8f649b075169fd0709764a4a2046c

Block reward is 50 grin
Fees should be considerably less than that (milligrins?)

![image](https://user-images.githubusercontent.com/30642645/34010254-ffbc87a4-e0d9-11e7-8a58-88df8d5f75ac.png)

**Comment by hendi** [comment]
If grin has 8 decimal places like Bitcoin, the fee in your screenshot would be 0.02 grin. If that assumption is correct I'll push a display fix for this tomorrow.

**Comment by antiochp** [comment]
Yeah I'm pretty sure we use 8 decimal places.
`50 grin == 5,000,000,000` (from mimblewimble/grin#232).

**Comment by antiochp** [comment]
Actually from the code here - 
https://github.com/mimblewimble/grin/pull/241/files

```
50 grin == 50,000,000,000
```

**Comment by hendi** [comment]
Sorry for the long wait, this should be fixed now.
