### ISSUE TITLE
view all block with total_difficulty greater than x

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin-explorer#12]
As a node operator it would be really useful to view blocks (chain heads?) that are known about that have higher total_difficulty than me.
Particularly in testnet1 with the wide variety of forks in play right now.

**Comment by sesam** [comment]
Dreaming up code for the block view page

````
        context["more_work_blocks_list"] = Block.objects.filter(height__gt=block.height)
````
 ... and then filter this down to only get the heads+tails of each chain without the blocks in between. Maybe nicely doable with something like a "sieve of Eratosthenes" but filtering block ancestors instead.

**Comment by antiochp** [comment]
Closing this as really old.
