### ISSUE TITLE
Compute difficulty from total difficulty

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-explorer#15]
After Update to Testnet2 https://github.com/mimblewimble/grin-explorer/pull/14 we need to compute the difficulty from the total difficulty.
See https://github.com/mimblewimble/grin/pull/777 for reference.
TLDR:
```
let target_difficulty = header.total_difficulty.clone() - prev.total_difficulty.clone();
```

**Comment by hendi** [comment]
Fixed with 7d89ab0
