### ISSUE TITLE
Cuckatoo-32 blocks can not be found

### ISSUE THREAD

**Issue by Lolliedieb** [mimblewimble/grin-explorer#47]
See for example blocks 430112 and 430255 which do not seem to exist on https://grinmint.com/explorer

**Comment by quentinlesceller** [comment]
Indeed. Good find. Seems like it is the same grinexplorer:

https://grinexplorer.net/search?q=430112

**Comment by Lolliedieb** [comment]
Right, while grinscan has them correct :) 
https://grinscan.net/block/430112

**Comment by hendi** [comment]
I haven't set `archive_mode=true` on my nodes, does anybody have the output of http://127.0.0.1:3413/blocks/00004c782afccb4ea6dee4579e3e2a23e2e6379b2a34502856811a78c58c15f3 so I can check what's going on?
