### ISSUE TITLE
Add output_mmr_size and kernel_mmr_size migration

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-explorer#56]
Necessary because of https://github.com/mimblewimble/grin/pull/3329

**Comment by hendi** [comment]
This is now live on the explorer: https://grinexplorer.net/block/000256d2fe46d21f9aa5c8d72cbfb835c78d1dc1502442c3fe3b7217afff578f

**Comment by quentinlesceller** [comment]
Nice thanks!
