### ISSUE TITLE
Explain the explorer's data source

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin-explorer#8]
Add a text box explaining data sources, something like

"Data in this explorer is collected from multiple grin servers in 4 geo locations. This makes it possible to detect forks, and many alternative blocks for same height can be seen in the explorers list of Recent blocks. This explorer aims to be the most accurate and up to date view of the grin blockchains. <and maybe a donate-link>"

**Comment by alirezajon** [comment]
> Add a text box explaining data sources, something like
> 
> "Data in this explorer is collected from multiple grin servers in 4 geo locations. This makes it possible to detect forks, and many alternative blocks for same height can be seen in the explorers list of Recent blocks. This explorer aims to be the most accurate and up to date view of the grin blockchains. "

**Comment by hendi** [comment]
The data sources a mentioned on https://grinexplorer.net/health now
